Species.create(:id => 1, :name => "acara")
Species.create(:id => 2, :name => "aisha")
Species.create(:id => 3, :name => "blumaroo")
Species.create(:id => 4, :name => "bori")
Species.create(:id => 5, :name => "bruce")
Species.create(:id => 6, :name => "buzz")
Species.create(:id => 7, :name => "chia")
Species.create(:id => 8, :name => "chomby")
Species.create(:id => 9, :name => "cybunny")
Species.create(:id => 10, :name => "draik")
Species.create(:id => 11, :name => "elephante")
Species.create(:id => 12, :name => "eyrie")
Species.create(:id => 13, :name => "flotsam")
Species.create(:id => 14, :name => "gelert")
Species.create(:id => 15, :name => "gnorbu")
Species.create(:id => 16, :name => "grarrl")
Species.create(:id => 17, :name => "grundo")
Species.create(:id => 18, :name => "hissi")
Species.create(:id => 19, :name => "ixi")
Species.create(:id => 20, :name => "jetsam")
Species.create(:id => 21, :name => "jubjub")
Species.create(:id => 22, :name => "kacheek")
Species.create(:id => 23, :name => "kau")
Species.create(:id => 24, :name => "kiko")
Species.create(:id => 25, :name => "koi")
Species.create(:id => 26, :name => "korbat")
Species.create(:id => 27, :name => "kougra")
Species.create(:id => 28, :name => "krawk")
Species.create(:id => 29, :name => "kyrii")
Species.create(:id => 30, :name => "lenny")
Species.create(:id => 31, :name => "lupe")
Species.create(:id => 32, :name => "lutari")
Species.create(:id => 33, :name => "meerca")
Species.create(:id => 34, :name => "moehog")
Species.create(:id => 35, :name => "mynci")
Species.create(:id => 36, :name => "nimmo")
Species.create(:id => 37, :name => "ogrin")
Species.create(:id => 38, :name => "peophin")
Species.create(:id => 39, :name => "poogle")
Species.create(:id => 40, :name => "pteri")
Species.create(:id => 41, :name => "quiggle")
Species.create(:id => 42, :name => "ruki")
Species.create(:id => 43, :name => "scorchio")
Species.create(:id => 44, :name => "shoyru")
Species.create(:id => 45, :name => "skeith")
Species.create(:id => 46, :name => "techo")
Species.create(:id => 47, :name => "tonu")
Species.create(:id => 48, :name => "tuskaninny")
Species.create(:id => 49, :name => "uni")
Species.create(:id => 50, :name => "usul")
Species.create(:id => 51, :name => "wocky")
Species.create(:id => 52, :name => "xweetok")
Species.create(:id => 53, :name => "yurble")
Species.create(:id => 54, :name => "zafara")

Color.create(:id => 1, :name => "alien", :basic => false, :standard => true)
Color.create(:id => 2, :name => "apple", :basic => false, :standard => false)
Color.create(:id => 3, :name => "asparagus", :basic => false, :standard => false)
Color.create(:id => 4, :name => "aubergine", :basic => false, :standard => false)
Color.create(:id => 5, :name => "avocado", :basic => false, :standard => false)
Color.create(:id => 6, :name => "baby", :basic => false, :standard => false)
Color.create(:id => 7, :name => "biscuit", :basic => false, :standard => true)
Color.create(:id => 8, :name => "blue", :basic => true, :standard => true)
Color.create(:id => 9, :name => "blueberry", :basic => false, :standard => false)
Color.create(:id => 10, :name => "brown", :basic => false, :standard => true)
Color.create(:id => 11, :name => "camouflage", :basic => false, :standard => true)
Color.create(:id => 12, :name => "carrot", :basic => false, :standard => false)
Color.create(:id => 13, :name => "checkered", :basic => false, :standard => true)
Color.create(:id => 14, :name => "chocolate", :basic => false, :standard => true)
Color.create(:id => 15, :name => "chokato", :basic => false, :standard => false)
Color.create(:id => 16, :name => "christmas", :basic => false, :standard => true)
Color.create(:id => 17, :name => "clay", :basic => false, :standard => true)
Color.create(:id => 18, :name => "cloud", :basic => false, :standard => true)
Color.create(:id => 19, :name => "coconut", :basic => false, :standard => true)
Color.create(:id => 20, :name => "custard", :basic => false, :standard => true)
Color.create(:id => 21, :name => "darigan", :basic => false, :standard => true)
Color.create(:id => 22, :name => "desert", :basic => false, :standard => true)
Color.create(:id => 23, :name => "disco", :basic => false, :standard => true)
Color.create(:id => 24, :name => "durian", :basic => false, :standard => false)
Color.create(:id => 25, :name => "electric", :basic => false, :standard => true)
Color.create(:id => 26, :name => "faerie", :basic => false, :standard => true)
Color.create(:id => 27, :name => "fire", :basic => false, :standard => true)
Color.create(:id => 28, :name => "garlic", :basic => false, :standard => true)
Color.create(:id => 29, :name => "ghost", :basic => false, :standard => true)
Color.create(:id => 30, :name => "glowing", :basic => false, :standard => true)
Color.create(:id => 31, :name => "gold", :basic => false, :standard => true)
Color.create(:id => 32, :name => "gooseberry", :basic => false, :standard => false)
Color.create(:id => 33, :name => "grape", :basic => false, :standard => false)
Color.create(:id => 34, :name => "green", :basic => true, :standard => true)
Color.create(:id => 35, :name => "grey", :basic => false, :standard => true)
Color.create(:id => 36, :name => "halloween", :basic => false, :standard => true)
Color.create(:id => 37, :name => "ice", :basic => false, :standard => true)
Color.create(:id => 38, :name => "invisible", :basic => false, :standard => true)
Color.create(:id => 39, :name => "island", :basic => false, :standard => true)
Color.create(:id => 40, :name => "jelly", :basic => false, :standard => true)
Color.create(:id => 41, :name => "lemon", :basic => false, :standard => false)
Color.create(:id => 42, :name => "lime", :basic => false, :standard => false)
Color.create(:id => 43, :name => "mallow", :basic => false, :standard => true)
Color.create(:id => 44, :name => "maraquan", :basic => false, :standard => false)
Color.create(:id => 45, :name => "msp", :basic => false, :standard => true)
Color.create(:id => 46, :name => "mutant", :basic => false, :standard => false)
Color.create(:id => 47, :name => "orange", :basic => false, :standard => false)
Color.create(:id => 48, :name => "pea", :basic => false, :standard => false)
Color.create(:id => 49, :name => "peach", :basic => false, :standard => false)
Color.create(:id => 50, :name => "pear", :basic => false, :standard => false)
Color.create(:id => 51, :name => "pepper", :basic => false, :standard => false)
Color.create(:id => 52, :name => "pineapple", :basic => false, :standard => false)
Color.create(:id => 53, :name => "pink", :basic => false, :standard => true)
Color.create(:id => 54, :name => "pirate", :basic => false, :standard => true)
Color.create(:id => 55, :name => "plum", :basic => false, :standard => false)
Color.create(:id => 56, :name => "plushie", :basic => false, :standard => true)
Color.create(:id => 57, :name => "purple", :basic => false, :standard => true)
Color.create(:id => 58, :name => "quigukiboy", :basic => false, :standard => true)
Color.create(:id => 59, :name => "quigukigirl", :basic => false, :standard => true)
Color.create(:id => 60, :name => "rainbow", :basic => false, :standard => true)
Color.create(:id => 61, :name => "red", :basic => true, :standard => true)
Color.create(:id => 62, :name => "robot", :basic => false, :standard => true)
Color.create(:id => 63, :name => "royalboy", :basic => false, :standard => true)
Color.create(:id => 64, :name => "royalgirl", :basic => false, :standard => true)
Color.create(:id => 65, :name => "shadow", :basic => false, :standard => true)
Color.create(:id => 66, :name => "silver", :basic => false, :standard => true)
Color.create(:id => 67, :name => "sketch", :basic => false, :standard => true)
Color.create(:id => 68, :name => "skunk", :basic => false, :standard => true)
Color.create(:id => 69, :name => "snot", :basic => false, :standard => true)
Color.create(:id => 70, :name => "snow", :basic => false, :standard => false)
Color.create(:id => 71, :name => "speckled", :basic => false, :standard => true)
Color.create(:id => 72, :name => "split", :basic => false, :standard => true)
Color.create(:id => 73, :name => "sponge", :basic => false, :standard => true)
Color.create(:id => 74, :name => "spotted", :basic => false, :standard => true)
Color.create(:id => 75, :name => "starry", :basic => false, :standard => true)
Color.create(:id => 76, :name => "strawberry", :basic => false, :standard => true)
Color.create(:id => 77, :name => "striped", :basic => false, :standard => true)
Color.create(:id => 78, :name => "thornberry", :basic => false, :standard => false)
Color.create(:id => 79, :name => "tomato", :basic => false, :standard => false)
Color.create(:id => 80, :name => "tyrannian", :basic => false, :standard => true)
Color.create(:id => 81, :name => "usukiboy", :basic => false, :standard => true)
Color.create(:id => 82, :name => "usukigirl", :basic => false, :standard => true)
Color.create(:id => 83, :name => "white", :basic => false, :standard => true)
Color.create(:id => 84, :name => "yellow", :basic => true, :standard => true)
Color.create(:id => 85, :name => "zombie", :basic => false, :standard => true)
Color.create(:id => 86, :name => "onion", :basic => false, :standard => false)
Color.create(:id => 87, :name => "magma", :basic => false, :standard => true)
Color.create(:id => 88, :name => "relic", :basic => false, :standard => true)
Color.create(:id => 89, :name => "woodland", :basic => false, :standard => true)
Color.create(:id => 90, :name => "transparent", :basic => false, :standard => true)
Color.create(:id => 91, :name => "maractite", :basic => false, :standard => true)
Color.create(:id => 92, :name => "8-bit", :basic => false, :standard => true)
Color.create(:id => 93, :name => "swamp gas", :basic => false, :standard => true)
Color.create(:id => 94, :name => "water", :basic => false, :standard => true)
Color.create(:id => 95, :name => "wraith", :basic => false, :standard => true)
Color.create(:id => 96, :name => "eventide", :basic => false, :standard => true)
Color.create(:id => 97, :name => "elderlyboy", :basic => false, :standard => true)
Color.create(:id => 98, :name => "elderlygirl", :basic => false, :standard => true)
Color.create(:id => 99, :name => "stealthy", :basic => false, :standard => true)
Color.create(:id => 100, :name => "dimensional", :basic => false, :standard => true)
